### ISSUE TITLE
Not work (zabbix 4.0)

### ISSUE THREAD

**Issue by CheckB** [krom/zabbix_template_md#6]
Hi.
On a host with debian 8, everything is ok, on a host with debian 9 in the detection rules: Unsupported item key.
What could be the problem?
p.s. zabbix 4.0

**Comment by CheckB** [comment]
If you execute all parameters from userparameter_md.conf, then they will execute correctly.

**Comment by krom** [comment]
Hi.
Execute this command
```bash
$ zabbix_get -s 192.168.0.3 -k 'md.discover'
{"data":[{"{#MDNAME}":"md0"}]}
```
Where 192.168.0.3 is your phisical server
You should store `userparameter_md.conf` at your server with MD Raid, but not Zabbix server.

If I execute this command, I have the same message because zabbix (localhost) server is virtual server w/o MD Raid.
```bash
$ zabbix_get -s localhost -k 'md.discover'
ZBX_NOTSUPPORTED: Unsupported item key.
```

**Comment by CheckB** [comment]
@krom 
![1](https://user-images.githubusercontent.com/34208261/53560131-c0d93080-3b5c-11e9-8d71-ab648fe90262.png)

**Comment by krom** [comment]
@CheckB 
`service zabbix-agent restart` // or another command
`zabbix_get -s localhost -k 'md.discover'`

?

**Comment by CheckB** [comment]
Of course I did a restart. And the problem with all the templates added, except for the standard ones from zabbix.

I would gladly conclude, but I can’t solve this problem yet:

zabbix_get [10193]: Check access restrictions in Zabbix agent configuration

**Comment by CheckB** [comment]
On Zabbix 3.0, everything works without problems.

**Comment by krom** [comment]
Did you import `template_md_4.0.xml`?
I created `template_md_3.0.xml` for zabbix v3 then migrated to zabbix 4.0 with exists template and params.

`template_md_4.0.xml` was added by PR

**Comment by CheckB** [comment]
I tried 3.0, 4.0.
Watched diff between 3.0 and 4.0. Nothing that could be a solution.

**Comment by krom** [comment]
Im closing issue this look like miss configuration.
