### ISSUE TITLE
Application with ID "" is not available on "Template MD Soft RAID".

### ISSUE THREAD

**Issue by alphaonex86** [krom/zabbix_template_md#7]
Hi, I have try your version 3.0 into 3.4, I have:
Application with ID "" is not available on "Template MD Soft RAID".
Cheers,

**Comment by bf0rce** [comment]
I imported template `template_md_3.0.xml` into Zabbix 3.4.11 and found no any problems. 
Everything is working.

**Comment by alphaonex86** [comment]
In my case it's Zabbix 3.4.15 Linux/Gentoo/MySQL

**Comment by krom** [comment]
It looks like issues with Zabbix configuration
