### ISSUE TITLE
Not work in zabbix-agent 4.0

### ISSUE THREAD

**Issue by denisbutov** [krom/zabbix_template_md#9]
Zabbix-agent 4.0 don't start with userparameter_md.conf.
CentOS Linux release 8.0.1905

```
Starting Zabbix Agent [nat.h1]. Zabbix 4.0.12 (revision fb4010108b).
**** Enabled features ****
IPv6 support:          YES
TLS support:           YES
**************************
using configuration file: /etc/zabbix_agentd.conf
agent #0 started [main process]
agent #1 started [collector]
agent #2 started [active checks #1]
active check "md.discover" is not supported: Unsupported item key.
Got signal [signal:15(SIGTERM),sender_pid:1,sender_uid:0,reason:0]. Exiting ...
Zabbix Agent stopped. Zabbix 4.0.12 (revision fb4010108b).
```

**Comment by krom** [comment]
Can you put here content of useagentd.conf

**Comment by denisbutov** [comment]
Problem resolved. In zabbix40-agent.x86_64 Centos 8 Include section zabbix_agentd.conf is empty and folder /etc/zabbix/zabbix_agentd.d not present. Solution: mkdir /etc/zabbix_agentd.conf.d, place userparameter_md.conf here and uncomment 
`Include=/etc/zabbix_agentd.conf.d/*.conf`
in /etc/zabbix/zabbix_agentd.conf
